### ISSUE TITLE
可不可以加入 下载磁力功能

### ISSUE THREAD

**Issue by 443344** [pcmid/waifud#2]
您的这个项目很好，bot用起来很方便，能够稍微进行一下改进就更完美了，以下我总结的一些问题和建议：
订阅成功没有回复，再次提交不会判断而是重复订阅   = = 

另外，可以的话，希望能够加入通过bot 下载磁力链的功能，或者单独弄一个项目 
github上 也有类似的项目，但是 aria2 都是在bot服务器上，不能通过 rpc 远程控制，不能机器人和aria2 分离  ，且项目不够轻量化 
您的这个项目就很好，可以 rpc 控制 aria2  

如果可以的话，也可以进行私下交流，感谢

类似的项目：
https://github.com/out386/aria-telegram-mirror-bot
https://github.com/psamim/aria2-telegram-bot

**Comment by pcmid** [comment]
唔 最近正在考虑重构的事情，以后可能会加上

**Comment by 443344** [comment]
欧克kkk，加油~~

**Comment by pcmid** [comment]
已跟新，完成了部分功能
* 订阅成功回复
* 重复订阅提醒
* bot 添加了 `/link` 命令，可以直接下载链接
