### ISSUE TITLE
运行getsub时错误

### ISSUE THREAD

**Issue by Yxue-1906** [pcmid/waifud#4]
![image](https://user-images.githubusercontent.com/20736038/83384098-1b74d280-a419-11ea-9b3a-cfbd685b7589.png)
如图，一旦运行getsub会出现错误并且闪退

**Comment by pcmid** [comment]
这个在最新的commit里修了

xueshao <notifications@github.com>于2020年6月1日 周一下午3:04写道：

**Comment by Yxue-1906** [comment]
了解了，我需要怎么修改呢？在源码中修改后再编译么？

另外出现下图错误，这是在订阅了动漫花园之后出现的（没有其他操作，仅sub）

![image](https://user-images.githubusercontent.com/20736038/83384575-21b77e80-a41a-11ea-974f-c946ed69771b.png)

**Comment by pcmid** [comment]
已经修了 感谢反馈
https://github.com/pcmid/waifud/releases/tag/v2.0.0-rc3

**Comment by Yxue-1906** [comment]
不客气，辛苦了！

另外是关于安装的问题，直接下载可执行文件会出现
![image](https://user-images.githubusercontent.com/20736038/83396310-5a615300-a42e-11ea-8717-1b7036c961dc.png)
这样的问题

一开始以为是没有配置好go的开发环境，但是直接使用go run跑源码可以运行（之前就是这样运行的），请问是哪一步操作出了问题呢？


另外是作为建议，可以在readme里稍微介绍一下dir是基于aria2配置的下载目录之上的，而不需要填写绝对路径（我被小坑了一把hhh

**Comment by Yxue-1906** [comment]
另外出现这个bug
![image](https://user-images.githubusercontent.com/20736038/83399218-68fe3900-a433-11ea-885e-be5e26153d2a.png)
![image](https://user-images.githubusercontent.com/20736038/83399276-829f8080-a433-11ea-9302-c4eea67ea217.png)

任务部分添加成功，大部分失败（不知道是添加成功显示添加失败还是，成功的未显示，失败的有提示），并且status命令无法获取任务状态

并且发现没有之前的任务成功提示了（可能是因为获取不到任务状态）

**Comment by pcmid** [comment]
> 不客气，辛苦了！
> 
> 另外是关于安装的问题，直接下载可执行文件会出现
> ![image](https://user-images.githubusercontent.com/20736038/83396310-5a615300-a42e-11ea-8717-1b7036c961dc.png)
> 这样的问题
> 
> 一开始以为是没有配置好go的开发环境，但是直接使用go run跑源码可以运行（之前就是这样运行的），请问是哪一步操作出了问题呢？
>

请问是下载的哪一个文件,又在什么机器上跑的 

> 另外是作为建议，可以在readme里稍微介绍一下dir是基于aria2配置的下载目录之上的，而不需要填写绝对路径（我被小坑了一把hhh

谢谢提醒

**Comment by pcmid** [comment]
> 另外出现这个bug
> ![image](https://user-images.githubusercontent.com/20736038/83399218-68fe3900-a433-11ea-885e-be5e26153d2a.png)
> ![image](https://user-images.githubusercontent.com/20736038/83399276-829f8080-a433-11ea-9302-c4eea67ea217.png)
> 
> 任务部分添加成功，大部分失败（不知道是添加成功显示添加失败还是，成功的未显示，失败的有提示），并且status命令无法获取任务状态
> 
> 并且发现没有之前的任务成功提示了（可能是因为获取不到任务状态）

请在最新的commit下 go run 试一下, 应该是改过的. 另外能否添加一个 `LOGLEVEL=TRACE` 的环境变量运行, 这个会打印出详细日志, 然后贴出来我看看

**Comment by Yxue-1906** [comment]
因为没有输出到文件 所以只有图片了
![image](https://user-images.githubusercontent.com/20736038/83409995-1d09bf00-a448-11ea-8435-c58a5b66be3a.png)
一部分可以添加成功，如上半部分
而错误信息还有这一种
![image](https://user-images.githubusercontent.com/20736038/83410051-39a5f700-a448-11ea-890d-87e504bf8b62.png)
不是很了解怎么使用最新commit，我是直接下载仓库然后上传解压，不知道这是不是最新commit了


> 另外是关于安装的问题，直接下载可执行文件会出现
> ![image](https://user-images.githubusercontent.com/20736038/83396310-5a615300-a42e-11ea-8717-1b7036c961dc.png)
> 这样的问题

我是用的linux arm64版本，刚查了一下，我的服务器是使用的amd的3900x，不知道是不是这个原因，因为时间关系我就没有更换amd64版本进行测试了

**Comment by pcmid** [comment]
> 因为没有输出到文件 所以只有图片了
> ![image](https://user-images.githubusercontent.com/20736038/83409995-1d09bf00-a448-11ea-8435-c58a5b66be3a.png)
> 一部分可以添加成功，如上半部分
> 而错误信息还有这一种
> ![image](https://user-images.githubusercontent.com/20736038/83410051-39a5f700-a448-11ea-890d-87e504bf8b62.png)
> 不是很了解怎么使用最新commit，我是直接下载仓库然后上传解压，不知道这是不是最新commit了

日志显示连接 aria2c 失败,是不是配置出错或者没启动呢

> 
> > 另外是关于安装的问题，直接下载可执行文件会出现
> > ![image](https://user-images.githubusercontent.com/20736038/83396310-5a615300-a42e-11ea-8717-1b7036c961dc.png)
> > 这样的问题
> 
> 我是用的linux arm64版本，刚查了一下，我的服务器是使用的amd的3900x，不知道是不是这个原因，因为时间关系我就没有更换amd64版本进行测试了

是的 x86_64 需要使用 amd64 的版本

**Comment by Yxue-1906** [comment]
确定启动了
第一张图片的上半部分显示添加成功

![image](https://user-images.githubusercontent.com/20736038/83411284-85f23680-a44a-11ea-8b98-ad010267d05a.png)

同时ariang也显示有300多个任务，应该错误不在aria2的配置


同时现在status命令没有响应了
![image](https://user-images.githubusercontent.com/20736038/83411442-d23d7680-a44a-11ea-8a24-fe775866c636.png)

另外时间安排原因，这周应该无法搭建与调试反馈了，还请多多担待。

辛苦了！

**Comment by pcmid** [comment]
多谢反馈 另外方便联系我 telegram 么, @pcmid
